// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGmj9xNLQSO6KMRWdRrV-xSGHJ-dFtisE',
    appId: '1:60760683691:web:a5d661ad7e3949b46933ee',
    messagingSenderId: '60760683691',
    projectId: 'pogoy-wild-animals',
    authDomain: 'pogoy-wild-animals.firebaseapp.com',
    databaseURL: 'https://pogoy-wild-animals-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pogoy-wild-animals.firebasestorage.app',
    measurementId: 'G-1KLJ2P3WF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdZjfl7qjVfepXqklLEp-D7-iTD9fBH_A',
    appId: '1:60760683691:android:9bf64dffb33479ae6933ee',
    messagingSenderId: '60760683691',
    projectId: 'pogoy-wild-animals',
    databaseURL: 'https://pogoy-wild-animals-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pogoy-wild-animals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiEcUVcdPgDhn6cffBhOIFcThPmNcLzKE',
    appId: '1:60760683691:ios:1912a96883003ae46933ee',
    messagingSenderId: '60760683691',
    projectId: 'pogoy-wild-animals',
    databaseURL: 'https://pogoy-wild-animals-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pogoy-wild-animals.firebasestorage.app',
    iosBundleId: 'com.example.wildAnimals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiEcUVcdPgDhn6cffBhOIFcThPmNcLzKE',
    appId: '1:60760683691:ios:1912a96883003ae46933ee',
    messagingSenderId: '60760683691',
    projectId: 'pogoy-wild-animals',
    databaseURL: 'https://pogoy-wild-animals-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pogoy-wild-animals.firebasestorage.app',
    iosBundleId: 'com.example.wildAnimals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGmj9xNLQSO6KMRWdRrV-xSGHJ-dFtisE',
    appId: '1:60760683691:web:8260b04e10bdbe7a6933ee',
    messagingSenderId: '60760683691',
    projectId: 'pogoy-wild-animals',
    authDomain: 'pogoy-wild-animals.firebaseapp.com',
    databaseURL: 'https://pogoy-wild-animals-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pogoy-wild-animals.firebasestorage.app',
    measurementId: 'G-6TGNF80EPG',
  );
}