import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:image_picker/image_picker.dart';
import 'package:tflite_flutter/tflite_flutter.dart';
import 'package:image/image.dart' as img;
import 'package:google_fonts/google_fonts.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

import 'splash_screen.dart';
import 'scan_history_service.dart';
import 'history_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the configuration we just set up
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Wild Animals Scanner',
      theme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.dark,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.tealAccent,
          brightness: Brightness.dark,
          surface: const Color(0xFF121212),
          background: const Color(0xFF121212),
        ),
        scaffoldBackgroundColor: const Color(0xFF121212),
        textTheme: GoogleFonts.poppinsTextTheme(ThemeData.dark().textTheme),
        appBarTheme: const AppBarTheme(
          centerTitle: true,
          elevation: 0,
          backgroundColor: Colors.transparent,
          foregroundColor: Colors.tealAccent,
        ),
      ),
      home: const SplashScreen(),
    );
  }
}

class ScannerPage extends StatefulWidget {
  const ScannerPage({super.key});

  @override
  State<ScannerPage> createState() => _ScannerPageState();
}

class _ScannerPageState extends State<ScannerPage> {
  File? _image;
  final picker = ImagePicker();

  Interpreter? _interpreter;
  List<String>? _labels;

  String _resultText = "Pick an image to scan";
  bool _isBusy = false;

  @override
  void initState() {
    super.initState();
    _loadModel();
    _loadLabels();
  }

  Future<void> _loadModel() async {
    try {
      _interpreter = await Interpreter.fromAsset('assets/model_unquant.tflite');
      debugPrint('Model loaded successfully');
    } catch (e) {
      debugPrint('Failed to load model: $e');
      setState(() {
        _resultText = "Error loading model. Check assets.";
      });
    }
  }

  Future<void> _loadLabels() async {
    try {
      final labelData = await rootBundle.loadString('assets/labels.txt');
      setState(() {
        _labels = labelData
            .split('\n')
            .map((line) => line.replaceAll(RegExp(r'^\d+\s*'), '').trim())
            .where((label) => label.isNotEmpty)
            .toList();
      });
      debugPrint('Labels loaded: ${_labels?.length} labels');
    } catch (e) {
      debugPrint('Failed to load labels: $e');
    }
  }

  @override
  void dispose() {
    _interpreter?.close();
    super.dispose();
  }

  Future<void> _pickImage(ImageSource source) async {
    if (_isBusy) return;
    setState(() => _isBusy = true);

    try {
      final picked = await picker.pickImage(source: source);
      if (picked != null) {
        setState(() => _image = File(picked.path));
        await _classifyImage(_image!);
      }
    } catch (e) {
      debugPrint("Error picking image: $e");
    }

    setState(() => _isBusy = false);
  }

  Future<void> _classifyImage(File imageFile) async {
    if (_interpreter == null || _labels == null) {
      setState(() => _resultText = "Model not loaded! Check assets folder.");
      return;
    }

    // Decode the image file
    final rawImage = img.decodeImage(imageFile.readAsBytesSync());
    if (rawImage == null) return;

    // Resize image to 224x224 as required by standard MobileNet/TeachableMachine models
    final resizedImage = img.copyResize(rawImage, width: 224, height: 224);

    // Convert image to Float32List (normalized 0.0 to 1.0)
    var inputBytes = Float32List(224 * 224 * 3);
    int index = 0;
    for (int y = 0; y < 224; y++) {
      for (int x = 0; x < 224; x++) {
        final pixel = resizedImage.getPixel(x, y);
        // Normalize to [-1, 1] for better accuracy with standard TFLite models
        inputBytes[index++] = (pixel.r - 127.5) / 127.5;
        inputBytes[index++] = (pixel.g - 127.5) / 127.5;
        inputBytes[index++] = (pixel.b - 127.5) / 127.5;
      }
    }

    // Reshape input and output for TFLite
    final input = inputBytes.reshape([1, 224, 224, 3]);
    final output =
        List.filled(_labels!.length, 0.0).reshape([1, _labels!.length]);

    // Run inference
    _interpreter!.run(input, output);

    // Parse results
    List<double> scores = List<double>.from(output[0]);
    double maxScore = 0;
    int maxIndex = -1;

    for (int i = 0; i < scores.length; i++) {
      if (scores[i] > maxScore) {
        maxScore = scores[i];
        maxIndex = i;
      }
    }

    setState(() {
      if (maxIndex != -1 && maxScore > 0.7) {
        String animalName = _labels![maxIndex];
        _resultText =
            "$animalName\nConfidence: ${(maxScore * 100).toStringAsFixed(1)}%";

        // Save to history
        ScanHistoryService().saveResult(ScanResult(
          animalName: animalName,
          confidence: maxScore,
          timestamp: DateTime.now(),
          imagePath: imageFile.path,
        ));
      } else {
        _resultText = "Unsure - Try again\n(Low Confidence)";
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        title: const Text('Scanner'),
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      body: Stack(
        children: [
          // Background Gradient
          Container(
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                colors: [Color(0xFF1A1A1A), Color(0xFF004D40)],
              ),
            ),
          ),
          Center(
            child: SingleChildScrollView(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  // Viewfinder
                  Container(
                    height: 320,
                    width: 320,
                    decoration: BoxDecoration(
                      color: Colors.black.withOpacity(0.3),
                      borderRadius: BorderRadius.circular(30),
                      border: Border.all(
                          color: Colors.tealAccent.withOpacity(0.5), width: 2),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withOpacity(0.5),
                          blurRadius: 20,
                          spreadRadius: 5,
                        ),
                      ],
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(28),
                      child: _image != null
                          ? Image.file(_image!, fit: BoxFit.cover)
                          : Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Icon(Icons.camera_alt_outlined,
                                    size: 60,
                                    color: Colors.white.withOpacity(0.5)),
                                const SizedBox(height: 10),
                                Text(
                                  "Tap buttons below\nto scan",
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.white.withOpacity(0.7),
                                    fontSize: 16,
                                  ),
                                ),
                              ],
                            ),
                    ),
                  ),
                  const SizedBox(height: 30),

                  // Result Card
                  if (_resultText.isNotEmpty &&
                      _resultText != "Pick an image to scan")
                    Container(
                      margin: const EdgeInsets.symmetric(horizontal: 40),
                      padding: const EdgeInsets.all(20),
                      decoration: BoxDecoration(
                        color: Colors.grey.shade900.withOpacity(0.9),
                        borderRadius: BorderRadius.circular(20),
                        border: Border.all(
                            color: Colors.tealAccent.withOpacity(0.3)),
                        boxShadow: [
                          BoxShadow(
                            color: Colors.black.withOpacity(0.3),
                            blurRadius: 10,
                            offset: const Offset(0, 5),
                          ),
                        ],
                      ),
                      child: Text(
                        _resultText,
                        style: GoogleFonts.poppins(
                          fontSize: 18,
                          fontWeight: FontWeight.w600,
                          color: Colors.tealAccent,
                        ),
                        textAlign: TextAlign.center,
                      ),
                    ),

                  const SizedBox(height: 20),
                  if (_isBusy)
                    const CircularProgressIndicator(color: Colors.white),
                ],
              ),
            ),
          ),
        ],
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
      floatingActionButton: Padding(
        padding: const EdgeInsets.only(bottom: 20),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            _buildCustomFab(
                Icons.photo_library, () => _pickImage(ImageSource.gallery)),
            const SizedBox(width: 20),
            _buildCustomFab(
                Icons.camera_alt, () => _pickImage(ImageSource.camera),
                isPrimary: true),
            const SizedBox(width: 20),
            _buildCustomFab(Icons.history, () {
              Navigator.push(
                context,
                MaterialPageRoute(builder: (context) => const HistoryPage()),
              );
            }),
          ],
        ),
      ),
    );
  }

  Widget _buildCustomFab(IconData icon, VoidCallback onPressed,
      {bool isPrimary = false}) {
    return Container(
      height: isPrimary ? 70 : 55,
      width: isPrimary ? 70 : 55,
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        gradient: isPrimary
            ? const LinearGradient(colors: [Colors.orange, Colors.deepOrange])
            : LinearGradient(
                colors: [Colors.grey.shade800, Colors.grey.shade900]),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.4),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Material(
        color: Colors.transparent,
        child: InkWell(
          onTap: onPressed,
          customBorder: const CircleBorder(),
          child: Icon(
            icon,
            color: isPrimary ? Colors.white : Colors.tealAccent,
            size: isPrimary ? 32 : 24,
          ),
        ),
      ),
    );
  }
}
